apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellonodejs
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-nodejs
    spec:
      containers:
      - image: hellonodejs:latest
        imagePullPolicy: IfNotPresent
        name: hellonodejs
        ports:
        - containerPort: 8080